### ISSUE TITLE
updateOrder failed with group sorting

### ISSUE THREAD

**Issue by LouisHrg** [optimistdigital/nova-sortable#45] opened 2020-09-07 11:31 UTC
Hello, 
I have a Post table, each post has a heading stored as string in a column (like news, podcasts, tests etc)
I've overridden buildSortQuery method in my Post model like so 
```
 public function buildSortQuery()
    {
        return static::query()
        ->where('heading', $this->heading);
    }
```

It works very well on creation, displaying, move to end, move to top. But when I want to use the drag and drop feature the nova api give me a HTTP 400 `resourceIds: invalid`

I don't know if i'm using buildSortQuery well, I tried to look into the code, on L75 in OptimistDigital\NovaSortable\Http\Controllers\SortableController, if i remove the buildSortQuery from the query it works as intended. 
Since we already getting the ids in the sorted scope (in my case, scoped by heading), do we really need to use the buildSortQuery on our model on this line ? 

Thanks in advance :smile:

**Comment by Tarpsvo** [comment] 2020-09-14 09:09
Hi! Can you confirm this still happens with version 1.4.14?

I can't reproduce this with the latest version.

**Comment by LouisHrg** [comment] 2020-09-16 14:31
Yeah it's still happening in 1.4.14

**Comment by Tarpsvo** [comment] 2020-09-18 07:14
What does the relationship look like? I can't reproduce this on my side yet. :S

**Comment by LouisHrg** [comment] 2020-09-22 12:42
It's not a relationship, it's a string field. 

My table : 
uuid id
string title
string content
string heading

And to filter the query by heading : 
```    
public function buildSortQuery() {
        return static::query()->where('heading', $this->heading);
 }
```

As said before, the probleme is on L75 in OptimistDigital\NovaSortable\Http\Controllers\SortableController

**Comment by danielztolnai** [comment] 2020-09-23 09:07
Hi! The problem appeared in 1.4.9 with 9fcf45fa5b1cc073370d3e9d3b30c007068c412f. In this commit, `buildSortQuery` is used on a newly created empty model instance. If `buildSortQuery` uses one of the attributes for example to filter by group, the given attribute will most likely be undefined on the new model and therefore `buildSortQuery` will return zero elements.

The perfect solution would be to run the `buildSortQuery` on the model we are changing, but there is no exact model indicated in the request, but every affected model in a list, like in this request example:
```
[
  "resourceId" => null
  "resourceIds" => array:3 [
    0 => 64
    1 => 63
    2 => 62
  ]
  "viaResource" => null
  "viaResourceId" => null
  "viaRelationship" => null
  "relationshipType" => null
  "relatedResource" => null
]
```

I think one solution could be to run `buildSortQuery` on one of the models in the `resourceIds` list, but I'm not sure if that works as intended every time. Another solution is to remove the change and not use `buildSortQuery` in `updateOrder()`, but I did not check how that would affect functionality.

**Comment by Tarpsvo** [comment] 2020-09-23 11:47
Gotcha fam, try out version 1.4.15. Should be fixed now.

**Comment by LouisHrg** [comment] 2020-09-23 12:03
Thanks you so much !!!!

**Closed** 2020-09-23 12:03 UTC
