### ISSUE TITLE
"undefined" tooltip

### ISSUE THREAD

**Issue by cord** [optimistdigital/nova-sortable#2] opened 2019-11-27 11:46 UTC
Great stuff - the long-awaited  sorting package!

Only issue I could find so far is the "undefined" tooltip:

![scopes 2019-11-27 12-45-05](https://user-images.githubusercontent.com/158588/69720848-d7281300-1113-11ea-9f41-c5b0558f0678.png)

**Comment by Tarpsvo** [comment] 2019-11-27 11:47
That's really weird. What version of Nova are you using?

**Comment by cord** [comment] 2019-11-27 11:48
latest 2.8

**Comment by Tarpsvo** [comment] 2019-11-28 08:05
I can't reproduce it, do you have any errors in the console maybe?

**Comment by cord** [comment] 2019-11-28 16:07
no errors in console.
the "undefined" tooltip appears only when moving the mouse above the burger icon. When moving above the arrows, the tooltip works correctly.

**Comment by Tarpsvo** [comment] 2019-12-05 09:02
I tried different browsers and did lots of testing, but was unable to reproduce it. Can you give a go at an attempt to fix it? I'm not even able to reproduce it.

My only guess would be that maybe you have a different version of `v-tooltip` installed in your project and that overrides the version Nova provides.

**Comment by cord** [comment] 2019-12-05 09:34
thanks a lot for checking, I think the reason for the issue might be

https://novapackages.com/packages/philperusse/nova-tooltip-field

which uses 
```
    "dependencies": {
        "tooltip.js": "^1.3.1",
        "vue": "^2.5.0"
    }
```
I will create an issue on this package

**Comment by Tarpsvo** [comment] 2019-12-05 09:48
Hmm, that package doesn't use the same tooltip packages as Nova though. Laravel Nova (and this package) use `"v-tooltip": "^2.0.2"`.

**Comment by Tarpsvo** [comment] 2020-01-03 12:04
Closing for now. Seems to be an environment issue on your side, as noone else has reported this. Best of luck!

**Closed by Tarpsvo** 2020-01-03 12:04 UTC
